
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "docker" do |d|
    #  d.post_install_provision "shell", inline:"echo \"y\" | sudo yum install vim"
    #  d.post_install_provision "shell", inline:"sudo echo -e \{\"hosts\":[\"tcp://192.168.33:2375\",\"unix:///var/run/docker.sock\"]\} > /etc/docker/daemon.json"
    # d.post_install_provision "shell", inline:$script
    d.post_install_provision "shell", path: "bootstrap.sh"
  end


end
